name: Tests

on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Testing generation
        run: docker-compose -f docker-compose.test.yml up --build --exit-code-from test
